data_path: /mnt/storageserver/workspace/kuru/sdfinetune/dataset/fulldanbooru
index_path: null
model_path: /mnt/storageserver/workspace/kuru/sdfinetune/checkpoints/animefull-64bs-0.1ucg-penultimate-clip-5epoch-50-50prompt/animefull-64bs-0.1ucg-penultimate-clip-5epoch-50-50prompt-68000.pt
config_path: /mnt/storageserver/workspace/kuru/sdfinetune/checkpoints/config.yaml
save_path: /mnt/storageserver/workspace/kuru/sdfinetune/checkpoints/animefull-64bs-0.1ucg-penultimate-clip-5epoch-50-50prompt-continue
do_save: true
run_name: animefull-64bs-0.1ucg-penultimate-clip-5epoch-50-50prompt-continue
lr: 1e-5
end_lr: 5e-6
warmup_steps: 100
anneal_steps: 370000
bs: 8
gas: 1
seed: 69
save_every: 2000
amp: false
loss_scale: false
cast_to: float16
sample_every: 500
beta1: 0.95
beta2: 0.999
eps: 1e-8
weight_decay: 0.0
use_ema: true
ucg: 0.1
min_tags: 50
max_tags: 50
mode: basedformer
epoch: 5